Repository sfeir-open-source/talk-control, pull requests merged in 2020-10, with the labels that each got.

#86 Add fontawesome to dropdown menu
  package-lock.json
  package.json
  src/client/layouts/presenter/presenter-mobile.html
  src/client/layouts/presenter/presenter.html
  src/client/web-components/menu-navigation/menu-navigation.js
  src/client/web-components/menu-plugins/menu-plugins.js
Labels: bug

#101 feat: Handle PageUp/PageDown keys
  config/config.json
  src/plugins/input/keyboard/index.js
  src/server/engines/revealjs-server-engine.js
  test/server/engines/revealjs-server-engine.spec.js
Labels: enhancement

#102 feat: Read webpack devServer port from config
  package.json
  webpack.config.common.js
  webpack.config.dev.js
Labels: enhancement

#107 fix: current slide height
  src/client/layouts/on-stage/index.css
  src/client/layouts/on-stage/on-stage.html
Labels: bug, hacktoberfest-accepted

#108 fix: reactivate husky
  .huskyrc.js
Labels: bug, hacktoberfest-accepted

#106 feat: #105 - add pull request and issue template
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest-accepted
